//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinetVeterinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistenti()
        {
            this.ProbeColectate = new HashSet<ProbeColectate>();
        }
    
        public int idAsistent { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<int> idMedic { get; set; }
    
        public virtual Medici Medici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProbeColectate> ProbeColectate { get; set; }
    }
}
