//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinetVeterinar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeVetEntities1 : DbContext
    {
        public HomeVetEntities1()
            : base("name=HomeVetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistenti> Asistenti { get; set; }
        public virtual DbSet<Cabinete> Cabinete { get; set; }
        public virtual DbSet<CabineteSectii> CabineteSectii { get; set; }
        public virtual DbSet<Consultatii> Consultatii { get; set; }
        public virtual DbSet<Intrebari> Intrebari { get; set; }
        public virtual DbSet<Medici> Medici { get; set; }
        public virtual DbSet<Pacienti> Pacienti { get; set; }
        public virtual DbSet<ProbeColectate> ProbeColectate { get; set; }
        public virtual DbSet<Programari> Programari { get; set; }
        public virtual DbSet<Raspunsuri> Raspunsuri { get; set; }
        public virtual DbSet<Sectii> Sectii { get; set; }
        public virtual DbSet<Specii> Specii { get; set; }
        public virtual DbSet<Utilizatori> Utilizatori { get; set; }
    }
}
