//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinetVeterinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacienti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacienti()
        {
            this.Programari = new HashSet<Programari>();
        }
    
        public int idPacient { get; set; }
        public Nullable<int> idUtilizator { get; set; }
        public Nullable<int> idSpecie { get; set; }
        public string Nume { get; set; }
        public int Varsta { get; set; }
        public decimal Greutate { get; set; }
    
        public virtual Specii Specii { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari> Programari { get; set; }
    }
}
