//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinetVeterinar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProbeColectate
    {
        public int idProba { get; set; }
        public Nullable<int> idAsistent { get; set; }
        public string TipProba { get; set; }
    
        public virtual Asistenti Asistenti { get; set; }
    }
}
